# Tắt bớt các thành phần cảnh báo không cần thiết để tiết kiệm RAM
alertmanager:
  enabled: false
pushgateway:
  enabled: false

extraScrapeConfigs: |
  - job_name: 'node-api'
    static_configs:
      - targets: ['node-api-service.default.svc.cluster.local:80']