version: '3.8'

services:
  postgres-primary:
    image: bitnamilegacy/postgresql:16
    container_name: postgres-primary
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=admin123
      - POSTGRESQL_PASSWORD=myuser_password
      - POSTGRESQL_USERNAME=myuser
      - POSTGRESQL_DATABASE=kamimind_db
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=replicator_password
    ports:
      - "5432:5432"
    volumes:
      - pg_primary_data:/bitnami/postgresql
      - ./postgresql.conf:/bitnami/postgresql/conf/postgresql.conf:ro

  postgres-replica:
    image: bitnamilegacy/postgresql:16
    container_name: postgres-replica
    depends_on:
      - postgres-primary
    environment:
      - POSTGRESQL_PASSWORD=myuser_password
      - POSTGRESQL_USERNAME=myuser
      - POSTGRESQL_DATABASE=kamimind_db
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_MASTER_HOST=postgres-primary  # Đổi từ pg-primary thành postgres-primary
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=replicator_password
    ports:
      - "5433:5432"
    volumes:
      - pg_replica_data:/bitnami/postgresql
      - ./postgresql.conf:/bitnami/postgresql/conf/postgresql.conf:ro

  pgpool:
    image: bitnamilegacy/pgpool:4.5.3-debian-12-r0
    container_name: pgpool
    depends_on:
      - postgres-primary
      - postgres-replica
    environment:
      - PGPOOL_ADMIN_USERNAME=admin
      - PGPOOL_ADMIN_PASSWORD=admin123
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=admin123
      - PGPOOL_SR_CHECK_USER=replicator
      - PGPOOL_SR_CHECK_PASSWORD=replicator_password
      - PGPOOL_BACKEND_NODES=0:postgres-primary:5432,1:postgres-replica:5432
      - PGPOOL_ENABLE_LOAD_BALANCING=yes
      - PGPOOL_ENABLE_LOG_PER_NODE_STATEMENT=yes
      - PGPOOL_LOAD_BALANCE_MODE=yes
      - PGPOOL_BACKEND_WEIGHTS=0:1
      - PGPOOL_POSTGRES_CUSTOM_USERS=myuser
      - PGPOOL_POSTGRES_CUSTOM_PASSWORDS=myuser_password
    ports:
      - "9999:9999"
  api:
    build: ./node_api
    container_name: my_node_api
    restart: always
    environment:
      - OTEL_SERVICE_NAME=my_python_api
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://tempo:4318/v1/traces
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
    ports: 
      - "3000:3000"
  nginx:
    image: nginx:alpine
    container_name: my_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - api
      - grafana

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: always


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"

  loki:
    image: grafana/loki:latest
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./observability/promtail-config.yml:/etc/promtail/config.yml:ro
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SERVER_DOMAIN=devoops.shop
      - GF_SERVER_ROOT_URL=https://devoops.shop/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ./observability/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./observability/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./observability/grafana/alerting:/etc/grafana/provisioning/alerting
    depends_on:
      - prometheus
      - loki
      - tempo
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./observability/tempo.yaml:/etc/tempo.yaml:ro
    ports:
      - "4317:4317"  
      - "4318:4318"  
      - "3200:3200"       
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: cadvisor
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - "8081:8080" 
volumes:
  pg_primary_data:
  pg_replica_data: