apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api
spec:
  selector:
    matchLabels:
      app: node-api
  template:
    metadata:
      labels:
        app: node-api
    spec:
      containers:
      - name: node-api
        image: hieuduong2509/my_node_api:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"     
            memory: "128Mi"  
          limits:
            cpu: "500m"      
            memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: node-api-service
spec:
  type: ClusterIP     
  selector:
    app: node-api    
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 3000